### ISSUE TITLE
Not able to run the utility from the latest commit

### ISSUE THREAD

**Issue by mraineri** [DMTF/python-redfish-utility#3]
Running using Python3, the utility comes up, but doesn't seem to take any action on commands that were given to it. Event the "exit" command doesn't close the tool

```
sudo python3 src/rdmc.py 
redfish : Redfish Utility version 1.0
--------------------------------------------------------------------------------
redfish > login <IP> -u <user> -p <password>
redfish > types
redfish > quit
redfish > exit
redfish > exit
redfish > exit
redfish > 
redfish > 
redfish >
```

Running using Python2, the utility just crashes; it's looking for the "queue" module, but in Python2, this module is "Queue".

```
sudo python2 src/rdmc.py 
Error locating extension LoadCommand at location extensions.COMMANDS.LoadCommand.LoadCommand
Traceback (most recent call last):
  File "src/rdmc.py", line 52, in <module>
   importlib.import_module(pkgName), cName)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/share/Redfish/python-redfish-utility/src/extensions/COMMANDS/LoadCommand.py", line 15, in <module>
    from queue import Queue
ImportError: No module named queue
```

**Comment by PrithviBS** [comment]
This should be fixed in the pull request (Fix to support python 2 and 3 compatibility.) Please check and respond once the pull request is approved.

**Comment by mraineri** [comment]
Thanks!

Closing 5/24
